### ISSUE TITLE
Need Help with builder

### ISSUE THREAD

**Issue by TerranBen666** [Callumgm/Cookies_RAT#2]
Hey, basically i need help with builder, i have python 3.9.7 installed and added as a path. I installed the requirements using pip install -r requirements.txt. Then I run setup and when i run the builder it instantly closes

**Comment by Callumgm** [comment]
add me on discord (found on github profile)

**Comment by TerranBen666** [comment]
Alright your discord is CookiesKush420#0001 right?

**Comment by Callumgm** [comment]
No no its CookiesKush420#9599
