### ISSUE TITLE
How to create exe file to send to the victim

### ISSUE THREAD

**Issue by Alansian** [Callumgm/Cookies_RAT#6]
I cant make the file too send too the target, i need help making the file too send i edited everything. I just cant make the file i dont understand how if anyone could help would be awsome

**Comment by Callumgm** [comment]
Please try using the new builder to create a payload, if you still have problems let me know here!

Tips:

- create a none remote payload if you have no idea what you're doing
- create a remote payload if you know what your doing

**Comment by Callumgm** [comment]
Currently under development still :(
